# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"D\n\x18\x43heckAvailabilityRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x14\n\x0crequired_qty\x18\x02 \x01(\x05\".\n\x19\x43heckAvailabilityResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\"@\n\x16UpdateInventoryRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x12\n\nchange_qty\x18\x02 \x01(\x05\"*\n\x17UpdateInventoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xcc\x01\n\x10InventoryService\x12^\n\x11\x43heckAvailability\x12#.inventory.CheckAvailabilityRequest\x1a$.inventory.CheckAvailabilityResponse\x12X\n\x0fUpdateInventory\x12!.inventory.UpdateInventoryRequest\x1a\".inventory.UpdateInventoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_start=30
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_end=98
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_start=100
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_end=146
  _globals['_UPDATEINVENTORYREQUEST']._serialized_start=148
  _globals['_UPDATEINVENTORYREQUEST']._serialized_end=212
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_start=214
  _globals['_UPDATEINVENTORYRESPONSE']._serialized_end=256
  _globals['_INVENTORYSERVICE']._serialized_start=259
  _globals['_INVENTORYSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
