# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\":\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x11\n\torder_qty\x18\x03 \x01(\x05\"1\n\x12\x43reateOrderRequest\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order\"2\n\x13\x43reateOrderResponse\x12\x1b\n\x05order\x18\x01 \x01(\x0b\x32\x0c.order.Order\"\x13\n\x11ListOrdersRequest\"2\n\x12ListOrdersResponse\x12\x1c\n\x06orders\x18\x01 \x03(\x0b\x32\x0c.order.Order2\x97\x01\n\x0cOrderService\x12\x44\n\x0b\x43reateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12\x41\n\nListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=22
  _globals['_ORDER']._serialized_end=80
  _globals['_CREATEORDERREQUEST']._serialized_start=82
  _globals['_CREATEORDERREQUEST']._serialized_end=131
  _globals['_CREATEORDERRESPONSE']._serialized_start=133
  _globals['_CREATEORDERRESPONSE']._serialized_end=183
  _globals['_LISTORDERSREQUEST']._serialized_start=185
  _globals['_LISTORDERSREQUEST']._serialized_end=204
  _globals['_LISTORDERSRESPONSE']._serialized_start=206
  _globals['_LISTORDERSRESPONSE']._serialized_end=256
  _globals['_ORDERSERVICE']._serialized_start=259
  _globals['_ORDERSERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
