# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"5\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"9\n\x14\x43reateProductRequest\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\":\n\x15\x43reateProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"7\n\x12GetProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"\x15\n\x13ListProductsRequest\":\n\x14ListProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"9\n\x14UpdateProductRequest\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"(\n\x15UpdateProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc4\x02\n\x0eProductService\x12N\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x1e.product.CreateProductResponse\x12\x45\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12K\n\x0cListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12N\n\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x1e.product.UpdateProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=26
  _globals['_PRODUCT']._serialized_end=79
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=81
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=138
  _globals['_CREATEPRODUCTRESPONSE']._serialized_start=140
  _globals['_CREATEPRODUCTRESPONSE']._serialized_end=198
  _globals['_GETPRODUCTREQUEST']._serialized_start=200
  _globals['_GETPRODUCTREQUEST']._serialized_end=231
  _globals['_GETPRODUCTRESPONSE']._serialized_start=233
  _globals['_GETPRODUCTRESPONSE']._serialized_end=288
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=290
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=311
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=313
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=371
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=373
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=430
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_start=432
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_end=472
  _globals['_PRODUCTSERVICE']._serialized_start=475
  _globals['_PRODUCTSERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
